# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voted_claims',
        ),
        migrations.AddField(
            model_name='claim',
            name='voters',
            field=models.ManyToManyField(related_name='_claim_voters_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
