# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_auto_20160515_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='answerers',
            field=models.ManyToManyField(related_name='_claim_answerers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
