# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_claim_answerers'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='type',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
