# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20160608_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.BooleanField(verbose_name='Is this philosophy?'),
        ),
    ]
