# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20160608_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
