# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_claim_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.BooleanField(default=True, verbose_name='Is this philosophy?'),
        ),
    ]
